specVersion: "0.2.0"

name: "Subql-Starter"
version: "0.0.0"
description: ""
repository: "https://github.com/subquery/subql-starter"

schema:
  file: "./schema.graphql"

network:
  genesisHash: '0x401a1f9dca3da46f5c4091016c8a2f26dcea05865116b286f60f668207d1474b' # Moonriver
  endpoint: wss://moonriver.api.onfinality.io/public-ws

  chaintypes:
    file: "./types.yaml"

dataSources:
  - kind: substrate/Moonbeam
    startBlock: 752073
    processor:
      file: './node_modules/@subql/contract-processors/dist/moonbeam.js'
    mapping:
      file: './dist/index.js'
      handlers:
        # - handler: handleMoonriverBlock
        #   kind: substrate/MoonriverBlock
        # - handler: handleMoonriverCall
        #   kind: substrate/MoonriverCall
        - handler: handleMoonriverEvent
          kind: substrate/MoonbeamEvent
          filter:
            address: '0x6bd193ee6d2104f14f94e2ca6efefae561a4334b'
            topics:
              - '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef' # Transfer(address,address,u256) event
              - null


